### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by ssjshields** [ssjshields/game-night-Pokemon#1]
- [x] add base set, jungle, fossil, team rocket, gym heroes, gym challenge assets
- [x] add base set 2 assets
- [x] rename base set 2 files
- [ ] sort alternative art cards (some basic named incorrectly)
- [x] add possessive punctuation to filenames
- [x] #2
- [ ] #3
- [ ] add play mat
- [ ] add deck boxes (storage)
- [ ] add box / booster pack art
- [x] add implement lua / tables
- [x] add misc lua / scripts
- [x] remove backgrounds from card backs and round all card edges
- [x] add workshop art
- [ ] implement paper api for rulebooks (like in dnd, cyberpunk, etc: https://github.com/Chuckleberry-Finn/zomboidPaper)

**Comment by Chuckleberry-Finn** [comment]
Can't include rule-sets, generally.
